language: php

php:
  - 5.4
  - 5.3

before_script:
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install

script: phpunit --configuration test/phpunit.xml

notifications:
  email: false
