language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

sudo: false

before_script:
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install

script: phpunit --configuration test/phpunit.xml

notifications:
  email: false
